sudo: false # container-based infrastructure
language: scala
scala:
 - 2.12.7
 - 2.11.12
 - 2.10.7
jdk: oraclejdk8
env:
 - WEBDRIVER_CHROME_DRIVER_SERVICE_URL=9222
script:
 - sbt ++$TRAVIS_SCALA_VERSION test
 - sbt ++$TRAVIS_SCALA_VERSION inttest
addons:
 chrome: stable
 apt:
  packages:
    - chromium-chromedriver
before_script:
 # start Chrome and listen on localhost
 - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &