language: scala
scala:
 - 2.12.7
 - 2.11.12
 - 2.10.7
jdk: openjdk8
env:
 - WEBDRIVER_CHROME_DRIVER="/usr/lib/chromium-browser/chromedriver"
script:
 - sbt ++$TRAVIS_SCALA_VERSION test
 - sbt ++$TRAVIS_SCALA_VERSION inttest
addons:
 chrome: stable
 apt:
  packages:
    - chromium-chromedriver
