github: [Repository metadata]
markdown: kramdown
url: https://www.scalawebtest.org
#for local server instances
#url: http://localhost:4000
defaults:
  -
    scope:
      path: ""
    values:
      scalaWebTestVersion: 3.0.0
collections:
  - mainNavItems
contextpath:
include: [_headers]
