github: [Repository metadata]
markdown: kramdown
#also change prefix in init.js, when changing the url
url: http://www.scalawebtest.org
scalaWebTestVersion: 1.0.0
collections:
  - mainNavItems
contextpath: