github: [Repository metadata]
markdown: kramdown
defaults:
  -
    scope:
      path: ""
    values:
      scalaWebTestVersion: 3.0.1
      slf4jVersion: 1.7.26
collections:
  - mainNavItems
contextpath:
include: [_headers]
