github: [Repository metadata]
markdown: kramdown
url: http://www.scalawebtest.org
#for local server instances
#url: http://localhost:4000
scalaWebTestVersion: 1.0.0
collections:
  - mainNavItems
contextpath: